---
title: "Data_Prep"
author: "Tingrui Huang"
date: "November 13, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Packages
```{r }
library(naniar)
library(tidyverse)
library(magrittr)
library(lme4)
library(ggcorrplot)
library(ggrepel)
library(scales)
library(GGally)
library(ggpubr)
```

### Load dataset into R
```{r }
kickstarter <- read.csv("C:/Users/Qilincaizi/Desktop/BU_MSSP/Fall_2018/MA678_Appl_Stat_Model/Midterm_Project/dataset/kickstarter.csv")
ks <- kickstarter
```
### Missing Value
```{r }
missingvalue <- function(df) {
        na_vals = sapply(df , function(x) mean(is.na(x)))
        nas = data.frame(column_names = names(na_vals) , na_percentage = as.vector(na_vals))
        ggplot(nas , aes(x = reorder(column_names , na_percentage) , y = na_percentage , label = paste(as.character(round(na_percentage * 100 , 1)) , "%"))) +
                geom_col(fill = "lightblue") + xlab('Names of columns') + ylab("NA's Percentage") +
                labs(title = "Column NA's Percentage") + geom_text(color = 'darkblue') + theme_minimal() + coord_flip()
}
missingvalue(ks)
```

### Data Cleaning
```{r }
options(scipen = 999)
# Reformat Deadline and Launched to Data
ks$deadline <- as.Date(ks$deadline, "%m/%d/%Y")
ks$launched <- as.Date(ks$launched, "%m/%d/%Y")
# Extract launched year and month
ks <- ks %>% mutate(launched_year=format(as.Date(launched, format="%m/%d/%Y"),"%Y"))
ks <- ks %>% mutate(launched_month=format(as.Date(launched, format="%m/%d/%Y"),"%m"))
# Found some projects launched in 1970. I believe these projects were canceled. Thus, remove these projects
ks <- ks[-c(2843,48148,75398,94580,247914,273780,319003),]
# Add new column to store duration of the project
ks <- ks %>% mutate(duration=as.integer(deadline-launched))
# Add new column to store the ratio of goal and pledged (use usd_goal_real and usd_pledged_real)
ks <- ks %>% mutate(ratio=round(usd_pledged_real/usd_goal_real, digits = 4))
# Found 4 projects have ratio smaller than 1 but classified as "successful"
ks$state[ks$ratio < 0.99999 & ks$state == "successful"] = "failed"
# Do the same for projects have ratio greater than 1 but classified as "failed"
ks$state[ks$ratio >= 1 & ks$state == "failed"] = "successful"
# Success and Fail
kssf <- ks %>% filter(state==c("successful","failed")) %>% droplevels()
```

### EDA
## Section 1. Background
# Part 1. Category vs Amount and Number of Projects
```{r, warning=FALSE}
# Most popular main categories and sub categories (by Number of Projects)
  # Main Category
ks <- within(ks, main_category <- factor(main_category, levels=names(sort(table(main_category), decreasing=TRUE))))
ggplot(ks,aes(x=main_category))+geom_histogram(stat = "count", binwidth = 1, fill="#0c4c8a")+ theme_minimal()+
                                      theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                                      xlab("Main Category") + ylab("Number of Projects") + 
                                      ggtitle("Most Popular Main Categories") 
      # Popular sub cat under Film and Video
film_video <- ks %>% filter(main_category=="Film & Video") %>% group_by(category) %>% count() %>% arrange(desc(n)) %>%
                                      ungroup() %>%
                                      mutate(category = factor(category, category)) %>%
                                      slice(1:15)
ggplot(film_video,aes(x=category,y=n))+geom_histogram(stat = "identity", fill="#0c4c8a")+ theme_minimal()+
                                      theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                                      xlab("Sub Category") + ylab("Number of Projects") + 
                                      ggtitle("Top 15 Popular Sub Categories under Film & Video")
  # Sub category
ks_category <- ks %>% group_by(category) %>% count() %>% arrange(desc(n)) %>% ungroup() %>% 
                                      mutate(category = factor(category, category)) %>% slice(1:15)
ggplot(ks_category,aes(x=category,y=n))+geom_histogram(stat = "identity", fill="#0c4c8a")+ theme_minimal()+
                                      theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                                      xlab("Sub Category") + ylab("Number of Projects") + 
                                      ggtitle("Top 15 Popular Sub Categories")

# Most popular main categories and sub categories (by Pledged Amount)
  # Main Category
mc_amount <- ks %>% group_by(main_category) %>% summarise(amount=sum(usd_pledged_real)) %>% arrange(desc(amount)) %>% 
                                          mutate(main_category = factor(main_category, main_category))
ggplot(mc_amount,aes(x=main_category, y=amount))+geom_histogram(stat = "identity", fill="#0c4c8a")+ 
                                      theme_minimal()+
                                      theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                                      xlab("Main Category") + ylab("Pledged Amount") + 
                                      ggtitle("Pledged Amount by Main Category") 
       # Popular sub cat under Games
games <- ks %>% filter(main_category=="Games") %>% group_by(category) %>% summarise(amount=sum(usd_pledged_real)) %>%
                                          arrange(desc(amount)) %>% 
                                          mutate(category = factor(category, category)) %>% ungroup() %>% slice(1:15)
ggplot(games,aes(x=category,y=amount))+geom_histogram(stat = "identity", fill="#0c4c8a")+ theme_minimal()+
                                      theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                                      xlab("Sub Category") + ylab("Pledged Amount") + 
                                      ggtitle("Top 15 Popular Sub Categories under Games")
  # Sub Category
sc_amount <- ks %>% group_by(category) %>% summarise(amount=sum(usd_pledged_real)) %>% arrange(desc(amount)) %>% 
                                          mutate(category = factor(category, category)) %>% ungroup() %>% slice(1:15)
ggplot(sc_amount,aes(x=category, y=amount))+geom_histogram(stat = "identity", fill="#0c4c8a")+ 
                                      theme_minimal()+
                                      theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                                      xlab("Sub Category") + ylab("Pledged Amount") + 
                                      ggtitle("Pledged Amount by Sub Category") 

# Average pledged amount per project for each Main Category
ave_p_mc <- ks %>% group_by(main_category, launched_year) %>%
                          mutate(total=length(ID),tt_amt=sum(usd_pledged_real),ave=(tt_amt/total)) %>% 
                          select(main_category,launched_year, ave) %>% unique()
ggplot(ave_p_mc,aes(x=main_category, y=ave))+geom_histogram(stat = "identity", fill="#0c4c8a")+
                                facet_wrap(~launched_year, ncol = 3)+
                                theme_minimal()+
                                theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                                xlab("Main Category") + ylab("Average Pledged Amount") + 
                                ggtitle("Average Pledged Amount per Project for each Main Category") 

ggplot(ave_p_mc,aes(x=launched_year, y=ave, fill=main_category))+geom_histogram(stat = "identity", position ="fill")+
                                theme_minimal()+
                                xlab("Main Category") + ylab("Average Pledged Amount") + 
                                ggtitle("Average Pledged Amount per Project for each Main Category") 
# Boxplot
ggplot(ks, aes(x=main_category, y=log(usd_pledged_real+1)))+geom_boxplot()+
                                geom_hline(aes(yintercept=mean(log(usd_pledged_real+1))),color="red")+
                                theme_minimal()+
                                theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                                xlab("Main Category") + ylab("Pledged Amount") + 
                                ggtitle("Pledged Amount Boxplot")
                                
```

# Part 2. Country vs Amount and Number of Projects
```{r warning=FALSE}
# Number of Projects
country_nop <- ks %>% group_by(country) %>% count() %>% arrange(desc(n)) %>% ungroup() %>% 
                                      mutate(country=factor(country,country))
ggplot(country_nop, aes(x=country, y=n)) + geom_histogram(stat = "identity", fill="#0c4c8a")+ 
                                      theme_minimal()+
                                      theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                                      xlab("Country") + ylab("Number of Projects") + 
                                      ggtitle("Number of Projects by Country") 
ggplot(ks, aes(x=country, y=usd_pledged_real))+geom_jitter()

# Amount
country_amt <- ks %>% group_by(country) %>% summarise(amount=sum(usd_pledged_real)) %>% arrange(desc(amount)) %>%
                        mutate(country = factor(country, country))
ggplot(country_amt,aes(x=country, y=amount))+geom_histogram(stat = "identity", fill="#0c4c8a")+ 
                                      theme_minimal()+
                                      theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                                      xlab("Country") + ylab("Pledged Amount") + 
                                      ggtitle("Pledged Amount by Country") 
```

# Part 3. Amount and Number of Projects by Year
```{r warning=FALSE}
# Amount by Year
amt_yr <- ks %>% group_by(launched_year) %>% summarise(amount=sum(usd_pledged_real)) %>% ungroup()
amt_yr$launched_year <- as.numeric(amt_yr$launched_year)
ggplot(amt_yr,aes(x=launched_year, y=amount))+geom_line(color="blue")+geom_point(color="red")+
          scale_x_continuous("Year of Launch", labels = as.character(amt_yr$launched_year), breaks = amt_yr$launched_year)+
          theme_minimal()+
          xlab("Year of Launch") + ylab("Total Pledged Amount for All Project") + 
          ggtitle("Total Pledged Amount by Year") 

# Number of Projects
ct_yr <- ks %>% group_by(launched_year) %>% count() %>% ungroup()
ct_yr$launched_year <- as.numeric(ct_yr$launched_year)
ggplot(ct_yr,aes(x=launched_year, y=n))+geom_line(color="blue")+geom_point(color="red")+
          scale_x_continuous("Year of Launch", labels = as.character(ct_yr$launched_year), breaks = ct_yr$launched_year)+
          theme_minimal()+
          xlab("Year of Launch") + ylab("Total Number of Projects") + 
          ggtitle("Total Number of Projects by Year") 
```

# Part. 4 Overall status and states by year
```{r warning=FALSE}
# Overall
ova_sta <- ks %>% group_by(state) %>% count() %>% ungroup() %>% mutate(prop=percent(n/sum(n)))
ggplot(ova_sta, aes(x=state, y=n))+geom_histogram(stat = "identity", fill="#0c4c8a")+
                                theme_minimal()+
                                xlab("Status") + ylab("Count") + 
                                ggtitle("Overall Status of Projects") 
ggplot(ova_sta, aes(x="", y=n, fill=state))+geom_bar(stat = "identity")+coord_polar("y")+
                                geom_text(aes(label = prop), position = position_stack(vjust = 0.5))

# By year
yr_sta <- ks %>% group_by(state, launched_year) %>% count() %>% ungroup()
ggplot(yr_sta,aes(x=launched_year, y=n))+geom_histogram(stat = "identity", fill="#0c4c8a")+facet_wrap(~state,ncol = 3)+
                                theme_minimal()+
                                xlab("Year of Launch") + ylab("Count") + 
                                ggtitle("Overall Status of Projects by Year") 
ggplot(yr_sta,aes(x=launched_year, y=n, fill=state))+geom_histogram(stat = "identity", position ="fill")+
                                theme_minimal()+
                                xlab("Year of Launch") + ylab("Count") + 
                                ggtitle("Overall Status of Projects by Year") 
```

# Part 5. Other Fantasy
```{r warning=FALSE}
# Average Goal Amount vs Average Pledged Ratio
goal_pratio <- ks %>% filter(ratio < quantile(ratio , probs = 0.99)) %>% group_by(main_category) %>% 
        summarise(mean_pledged = mean(ratio) , mean_goal = mean(usd_goal_real))
ggplot(goal_pratio, aes(x = mean_pledged , y = mean_goal , label = main_category , color = main_category)) + 
        geom_point(size = 3) + geom_text(vjust = -0.75) + xlim(c(0.3 , 1.15)) + ylim(c(0 , 115000)) +
        theme(legend.position = 'none') + 
        labs(x = 'Average Pledged Ratio' , y = 'Average Goal Amount')

# Category with Most failed projects and successful projects
fail <- ks %>% filter(state=="failed") %>% group_by(main_category, launched_year) %>% count() %>% ungroup()
fail %<>% filter(launched_year==c(2015,2016,2017))
ggplot(fail, aes(x=main_category, y=n))+geom_histogram(stat = "identity", fill="#0c4c8a")+
                facet_wrap(~launched_year, ncol = 3)+
                theme_minimal()+
                theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                xlab("Main Category") + ylab("Number of Project") + 
                ggtitle("Number of Failed Project by Category")

success <- ks %>% filter(state=="successful") %>% group_by(main_category, launched_year) %>% count() %>% ungroup()
ggplot(success, aes(x=main_category, y=n))+geom_histogram(stat = "identity", fill="#0c4c8a")+
                facet_wrap(~launched_year, ncol = 3)+
                theme_minimal()+
                theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                xlab("Main Category") + ylab("Number of Project") + 
                ggtitle("Number of Successful Project by Category") 
# Top 15 Fund raisers in 2017
t15fr <- ks %>% arrange(desc(usd_pledged_real)) %>% filter(launched_year==2017) %>% slice(1:15) %>%
                select(name,usd_pledged_real,category)%>%
                mutate(name=factor(name,name))

ggplot(t15fr, aes(x=name, y=usd_pledged_real, fill=category))+geom_histogram(stat = "identity")+
                theme_minimal()+
                theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                xlab("Sub Category") + ylab("Pledged Amount") + 
                ggtitle("15 Sub Categories with Highest Pledged Amount in 2017")+
                scale_x_discrete(labels= c("Tabletop Games","Wearables","Tabletop Games",
                                           "Product Design","Hardware","Tabletop Games",
                                           "Design", "Tabletop Games", "Product Design",
                                           "Video Games","Wearables","Tabletop Games",
                                           "Tabletop Games", "Sound","Camera Equipment"))
# Category-wise Success and Failure in 2016 and 2017
spmc <- ks %>% filter(launched_year==c(2016,2017)) %>% group_by(main_category, state) %>% count()
ggplot(spmc, aes(x=main_category, y=n, fill=state))+geom_histogram(stat = "identity", position="fill")+
                theme_minimal()+
                theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                xlab("Main Category") + ylab("Percentage") + 
                ggtitle("Category-wise Success and Failure in 2016 and 2017")

# Average funds raised per backer in different categories
perbacker <- ks %>% filter(launched_year==c(2009:2017))%>% group_by(main_category, launched_year) %>%
                summarise(avg=sum(usd_pledged_real)/sum(backers))
ggplot(perbacker, aes(x=main_category, y=avg))+geom_histogram(stat = "identity", fill="#0c4c8a")+
                facet_wrap(~launched_year, ncol=3)+
                theme_minimal()+
                theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                xlab("Main Category") + ylab("Average Fund per Backer") + 
                ggtitle("Average funds raised per backer")

# Success rate by category
srate <- ks %>% group_by(category, state) %>% select(goal, pledged, backers) %>% summarise(total=n()) %>%
  mutate(success_rate = percent(total/sum(total))) %>% filter(state == "successful") %>% 
  arrange(desc(success_rate)) %>% ungroup() %>% slice(1:10)
ggplot(srate, aes(x=reorder(category, -success_rate), y=success_rate))+
  geom_histogram(stat = "identity", fill="#0c4c8a")+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  xlab("Sub Category") + ylab("Success Rate") + 
  ggtitle("10 Most Successful Categories")+
  geom_text(aes(label=percent(success_rate)), vjust=-0.25)
```


# Part 6. Correlation
```{r }
cor_tst <- ks %>% select(backers, usd_pledged_real, usd_goal_real, duration, ratio, launched_year) %>%
                  na.omit()
cor_tst$launched_year <- as.numeric(cor_tst$launched_year)
ggpairs(cor_tst)

# Duration vs Amount
g1 <- ggplot(ks,aes(x=duration, y=log(usd_pledged_real+1), color=main_category))+
                geom_point(color="grey")+stat_smooth(method = "lm")+
                theme_minimal()+
                xlab("Duration") + ylab("Log Pledged Amount") + 
                ggtitle("Duration vs Log Amount")
# Backers vs Amount
g2 <- ggplot(ks,aes(x=log(backers+1), y=log(usd_pledged_real+1), color=main_category))+
                geom_point(color="grey")+stat_smooth(method = "lm")+
                theme_minimal()+
                xlab("Number of Backers") + ylab("Log Pledged Amount") + 
                ggtitle("Number of Backers vs Log Amount")
# Year vs Amount
g3 <- ggplot(ks,aes(x=as.numeric(launched_year), y=log(usd_pledged_real+1), color=main_category))+
                geom_point(color="grey")+stat_smooth(method = "lm")+
                theme_minimal()+
                xlab("Year of Launch") + ylab("Log Pledged Amount") + 
                ggtitle("Year of Launch vs Log Amount")
# Goal vs Pledged
g4 <- ggplot(ks,aes(x=log(usd_goal_real+1), y=log(usd_pledged_real+1), color=main_category))+
                geom_point(color="grey")+stat_smooth(method = "lm")+
                theme_minimal()+
                xlab("Log Goal") + ylab("Log Pledged Amount") + 
                ggtitle("Log Goal Amount vs Log Amount")
 
ggarrange(g1, g2, g3, g4, ncol=2, nrow=2, common.legend = TRUE, legend="bottom")
```
