---
title: "Modeling_Success"
author: "Tingrui Huang"
date: "December 2, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Package
```{r }
library(tidyverse)
library(Matrix)
library(lme4)
library(coefplot)
library(kableExtra)
library(stargazer)
library(carData)
library(car)
library(alr3)
library(zoo)
library(lmtest)
library(sjPlot)
library(sjlabelled)
library(sjmisc)
library(magrittr)
library(MASS)
library(arm)
library(lattice)
library(caret)
library(gplots)
library(ROCR)
library(rstanarm)
library(Rcpp)
```

### Import dataset and Preparation
```{r }
kickstarter <- read.csv("C:/Users/Qilincaizi/Desktop/BU_MSSP/Fall_2018/MA678_Appl_Stat_Model/Midterm_Project/dataset/kickstarter.csv")
ks <- kickstarter
# Reformat Deadline and Launched to Data
ks$deadline <- as.Date(ks$deadline, "%m/%d/%Y")
ks$launched <- as.Date(ks$launched, "%m/%d/%Y")
# Extract launched year and month
ks <- ks %>% mutate(launched_year=format(as.Date(launched, format="%m/%d/%Y"),"%Y"))
ks <- ks %>% mutate(launched_month=format(as.Date(launched, format="%m/%d/%Y"),"%m"))
# Found some projects launched in 1970. I believe these projects were canceled. Thus, remove these projects
ks <- ks[-c(2843,48148,75398,94580,247914,273780,319003),]
# Add new column to store duration of the project
ks <- ks %>% mutate(duration=as.integer(deadline-launched))
# Add new column to store the ratio of goal and pledged (use usd_goal_real and usd_pledged_real)
ks <- ks %>% mutate(ratio=round(usd_pledged_real/usd_goal_real, digits = 4))
# Found 4 projects have ratio smaller than 1 but classified as "successful"
ks$state[ks$ratio < 0.99999 & ks$state == "successful"] = "failed"
# Do the same for projects have ratio greater than 1 but classified as "failed"
ks$state[ks$ratio >= 1 & ks$state == "failed"] = "successful"
# Success and Fail
kssf <- ks %>% filter(state==c("successful","failed")) %>% droplevels()
kssf %<>% mutate(state=ifelse(state=="successful",1,0))  # Success=1, Failed=0


```

## Data Partition
```{r }
set.seed(999)
dp_index_sf <- rbinom(length(kssf$ID),1,prob = 0.7)
df_train_sf <- as.data.frame(kssf[dp_index_sf==1,])
df_test_sf <- as.data.frame(kssf[dp_index_sf==0,])
# Remove Null Island
df_train_sf %<>% filter(country!="Null Island")
df_test_sf %<>% filter(country!="Null Island")
```

## Scale variables
```{r }
df_train_sf$duration.c <- scale(df_train_sf$duration)
df_train_sf$usd_goal_real.c <- scale(df_train_sf$usd_goal_real)
df_test_sf$duration.c <- scale(df_test_sf$duration)
df_test_sf$usd_goal_real.c <- scale(df_test_sf$usd_goal_real)
```

## Variable selection
Outcome variables - state
Input variables - 
    Fixed effects: (backers), duration, usd_goal_real
    Random effects: main_category:category, country, launched_year
    
## Classic Logistic Regression
```{r }
# Fit a simple logistic regression
lor1 <- glm(state~log(backers+1), data = df_train_sf, family = binomial)
summary(lor1)
# Plot model
predfun<- function(x){ 
  invlogit (cbind (1,x) %*% coef(lor1))
  }
ggplot(df_train_sf)+aes(x=log(backers+1),y=state,colour=factor(state)) + 
  geom_jitter(height = 0.1)+stat_function(fun=predfun, col="black")
# Residual Plot
binnedplot(fitted(lor1),resid(lor1,type="response"))

```

```{r }
# Add duration
lor2 <- glm(state~log(backers+1)+duration, data = df_train_sf, family = binomial)
summary(lor2)
# Deviance reduced by 2000
# Plot model
predfun2<- function(x){ 
  invlogit (cbind (1,x,60) %*% coef(lor2))
  }
ggplot(df_train_sf)+aes(x=log(backers+1),y=state,colour=factor(state)) + 
  geom_jitter(height = 0.1)+stat_function(fun=predfun2, col="black")
# Residual Plot
binnedplot(fitted(lor2),resid(lor2,type="response"))
```

```{r }
# Add usd_goal_real
lor3 <- glm(state~log(backers+1)+duration.c+log(usd_goal_real+1), data = df_train_sf, family = binomial)
summary(lor3)
# Deviance redeced by 36000
# Plot model
predfun3<- function(x){ 
  invlogit (cbind (1,x,60,11) %*% coef(lor3)) # 60days, 100,000 goal amount
  }
ggplot(df_train_sf)+aes(x=log(backers+1),y=state,colour=factor(state)) + 
  geom_jitter(height = 0.1)+stat_function(fun=predfun3, col="black")
# Residual Plot
binnedplot(fitted(lor3),resid(lor3,type="response"))
# marginal plot
marginalModelPlot(lor3)
```

```{r }
# Add main_category
lor4 <- glm(state~log(backers+1)+duration+log(usd_goal_real+1)+main_category, 
            data = df_train_sf, family = binomial)
summary(lor4)
# Deviance reduced by 4000 
# Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred
# Residual Plot
binnedplot(fitted(lor4),resid(lor4,type="response"))
```

```{r }
# Add country
lor5 <- glm(state~log(backers+1)+duration+log(usd_goal_real+1)+main_category+country, 
            data = df_train_sf, family = binomial)
summary(lor5)
# Deviance redeced by 900
# Residual Plot
binnedplot(fitted(lor5),resid(lor5,type="response"))
```

```{r }
# Add launched year
lor6 <- glm(state~log(backers+1)+duration+log(usd_goal_real+1)+main_category+country+as.numeric(launched_year), 
            data = df_train_sf, family = binomial)
summary(lor6)
# Deviance reduced by 200
# Residual Plot
binnedplot(fitted(lor6),resid(lor6,type="response"))
```

```{r }
# Add interaction backer:main_category
lor7 <- glm(state~log(backers+1)+main_category+log(backers+1):main_category+duration.c+log(usd_goal_real+1)+
              country+launched_year, data = df_train_sf, family = binomial)
summary(lor7)
# Deviance reduced by 700
coefplot(lor7)
# Residual Plot
binnedplot(fitted(lor7),resid(lor7,type="response"))
# ROC - receiver operating characteristics (ROC) curve is a plot of the True positive rate as a function of false positive rate
fitted.y = fitted(lor7); observed.y= lor7$y
perf<- performance(prediction(fitted.y,observed.y) ,"tpr","fpr")
plot(perf); abline(0,1,lty=2)
# AUC - Area under the ROC curve is a measure of predictive power and called concordance index.
auc<- performance(prediction(fitted.y,observed.y) ,"auc") # AUC
auc@y.values[[1]]
```

```{r }
# Use model 7 to make prediction
lor_prob <- predict(lor7, newdata = df_test_sf, type = "response")
lor_pred <- ifelse(lor_prob>0.5,1,0)
lor_pred <- as.factor(lor_pred)
confusionMatrix(lor_pred, as.factor(df_test_sf$state))

# Since we don't know the number of backers
df_test_sf %<>% group_by(category) %>% mutate(backers=round(mean(backers),2))

```

```{r }
# Remove number of backers
lor8 <- glm(state~main_category+duration+log(usd_goal_real+1)+main_category:log(usd_goal_real+1)+
              country+as.numeric(launched_year), data = df_train_sf, family = binomial)
summary(lor8)
# Residual Plot
binnedplot(fitted(lor8),resid(lor8,type="response"))
# Prediction
lor_prob <- predict(lor8, newdata = df_test_sf, type = "response")
lor_pred <- ifelse(lor_prob>0.5,1,0)
lor_pred <- as.factor(lor_pred)
confusionMatrix(lor_pred, as.factor(df_test_sf$state))
# ROC - receiver operating characteristics (ROC) curve is a plot of the True positive rate as a function of false positive rate
fitted.y.2 = fitted(lor8); observed.y.2= lor8$y
perf2<- performance(prediction(fitted.y.2,observed.y.2) ,"tpr","fpr")
plot(perf2); abline(0,1,lty=2)
# AUC - Area under the ROC curve is a measure of predictive power and called concordance index.
auc2<- performance(prediction(fitted.y.2,observed.y.2) ,"auc") # AUC
auc2@y.values[[1]]
```

```{r }
# Anova
anova(lor1,lor3,lor6,lor7,lor8)
```

## Multilevel Logistic Reg
```{r }
# Simple ML Logistic Reg
mllo1 <- glmer(state~log(backers+1)+(1|main_category/category), data = df_train_sf, family = binomial)
summary(mllo1)
# Residual Plot
binnedplot(fitted(mllo1),resid(mllo1,type="response"))
```

```{r }
# Add duration
mllo2 <- glmer(state~log(backers+1)+duration.c+(1|main_category/category), data = df_train_sf, family = binomial)
summary(mllo2)
# Residual Plot
binnedplot(fitted(mllo2),resid(mllo2,type="response"))
```

```{r }
# Add usd_goal_real
mllo3 <- glmer(state~log(backers+1)+duration.c+log(usd_goal_real+1)+scale(as.numeric(launched_year))+
                 (1|main_category/category), data = df_train_sf, family = binomial)
summary(mllo3)
# Residual Plot
binnedplot(fitted(mllo3),resid(mllo3,type="response"))
```

```{r }
# Add more groups, country
mllo4 <- glmer(state~log(backers+1)+duration.c+log(usd_goal_real)+(1|main_category/category)+(1|country), 
               data = df_train_sf, family = binomial)
summary(mllo4)
# Residual Plot
binnedplot(fitted(mllo4),resid(mllo4,type="response"))
```

```{r }
# Add launched_year
mllo5 <- glmer(state~log(backers+1)+duration.c+log(usd_goal_real)+(1|main_category/category)+(1|country)+
                 scale(as.numeric(launched_year)), data = df_train_sf, family = binomial)
summary(mllo5)
# Residual Plot
binnedplot(fitted(mllo5),resid(mllo5,type="response"))
# Prediction
mllo5_prob <- predict(mllo5, newdata = df_test_sf, type = "response")
mllo5_pred <- ifelse(mllo5_prob>0.5,1,0)
mllo5_pred <- as.factor(mllo5_pred)
confusionMatrix(mllo5_pred, as.factor(df_test_sf$state))
```

```{r }
# Vary slope: backers
mllo6 <- glmer(state~log(backers+1)+duration.c+log(usd_goal_real)+(1+log(backers+1)|main_category/category)+
                 scale(as.numeric(launched_year)), data = df_train_sf, family = binomial)
summary(mllo6)
# Residual Plot
binnedplot(fitted(mllo6),resid(mllo6,type="response"))
# Prediction
mllo6_prob <- predict(mllo6, newdata = df_test_sf, type = "response")
mllo6_pred <- ifelse(mllo6_prob>0.5,1,0)
mllo6_pred <- as.factor(mllo6_pred)
confusionMatrix(mllo6_pred, as.factor(df_test_sf$state))
#
head(ranef(mllo6))
```

```{r }
mllo7 <- glmer(state~duration.c+log(usd_goal_real)+(1|main_category/category)+(1|country)+
                 as.numeric(launched_year), data = df_train_sf, family = binomial)
summary(mllo7)
# Residual Plot
binnedplot(fitted(mllo7),resid(mllo7,type="response"))
```

```{r }
# Compare model
anova(mllo3, mllo5, mllo6, lor7, lor8)
```

```{r }
df_stan_index <- sample(length(df_train_sf$ID),8000,replace = FALSE)
df_stan <- df_train_sf[df_stan_index,]
mllo6_st <- stan_glmer(state~log(backers+1)+duration.c+log(usd_goal_real)+
                         (1+log(backers+1)|main_category/category)+scale(as.numeric(launched_year)), 
                       data = df_stan,iter=300,chains=1,family = binomial)
pp_check(mllo6_st,plotfun = "intervals")
```