---
title: "Modeling"
author: "Tingrui Huang"
date: "November 30, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Package
```{r }
library(tidyverse)
library(MASS)
library(Matrix)
library(lme4)
library(coefplot)
library(kableExtra)
library(stargazer)
library(carData)
library(car)
library(alr3)
library(zoo)
library(lmtest)
library(sjPlot)
library(sjlabelled)
library(sjmisc)
library(pscl)
library(sandwich)
library(rstanarm)
library(Rcpp)
```

### Import dataset and Preparation
```{r }
kickstarter <- read.csv("C:/Users/Qilincaizi/Desktop/BU_MSSP/Fall_2018/MA678_Appl_Stat_Model/Midterm_Project/Kickstarter_project/dataset/kickstarter.csv")
ks <- kickstarter
# Reformat Deadline and Launched to Data
ks$deadline <- as.Date(ks$deadline, "%m/%d/%Y")
ks$launched <- as.Date(ks$launched, "%m/%d/%Y")
# Extract launched year and month
ks <- ks %>% mutate(launched_year=format(as.Date(launched, format="%m/%d/%Y"),"%Y"))
ks <- ks %>% mutate(launched_month=format(as.Date(launched, format="%m/%d/%Y"),"%m"))
# Found some projects launched in 1970. I believe these projects were canceled. Thus, remove these projects
ks <- ks[-c(2843,48148,75398,94580,247914,273780,319003),]
# Add new column to store duration of the project
ks <- ks %>% mutate(duration=as.integer(deadline-launched))
# Add new column to store the ratio of goal and pledged (use usd_goal_real and usd_pledged_real)
ks <- ks %>% mutate(ratio=round(usd_pledged_real/usd_goal_real, digits = 4))
# Found 4 projects have ratio smaller than 1 but classified as "successful"
ks$state[ks$ratio < 0.99999 & ks$state == "successful"] = "failed"
# Do the same for projects have ratio greater than 1 but classified as "failed"
ks$state[ks$ratio >= 1 & ks$state == "failed"] = "successful"
# Success and Fail
kssf <- ks %>% filter(state==c("successful","failed")) %>% droplevels()
```

### Modeling
## Variable selection
Outcome variables - usd_pledged_real
Input variables - 
    Fixed effects: (backers), duration, usd_goal_real
    Random effects: main_category:category, country, launched_year
    
## Data Partition
```{r }
set.seed(999)
dp_index <- rbinom(length(ks$ID),1,prob = 0.7)
df_train <- as.data.frame(ks[dp_index==1,])
df_test <- as.data.frame(ks[dp_index==0,])
df_train_hd <- df_train %>% mutate(non_zero=ifelse(usd_pledged_real==0,0,1))
df_test_hd <- df_test %>% mutate(non_zero=ifelse(usd_pledged_real==0,0,1))

```

## Scale variables
```{r }
df_train$duration.c <- scale(df_train$duration)
df_train$usd_goal_real.c <- scale(df_train$usd_goal_real)
df_test$duration.c <- scale(df_test$duration)
df_test$usd_goal_real.c <- scale(df_test$usd_goal_real)
df_train_hd$duration.c <- scale(df_train_hd$duration)
df_train_hd$usd_goal_real.c <- scale(df_train_hd$usd_goal_real)
df_test_hd$duration.c <- scale(df_test_hd$duration)
df_test_hd$usd_goal_real.c <- scale(df_test_hd$usd_goal_real)
nozero$duration.c <- scale(nozero$duration)
```

## Pledged Amount
# Classic Linear Regression
```{r }
# Model
lr1 <- lm(log(usd_pledged_real+1)~backers+duration+main_category+country+as.numeric(launched_year)+
            log(usd_goal_real+1), data = df_train)
summary(lr1)
  # Residual plot
plot(lr1, which = 1)
# Confidence interval
coefplot(lr1)
kable(head(confint(lr1)))
# Actual vs Fitted
plot(log(df_train$usd_pledged_real), fitted(lr1),xlab="actual value",ylab="fitted values")+
  abline(v=15,h=15,0,1, col="red")
```

```{r }
# Model - add log on backers and usd_goal_real
lr2 <- lm(log(usd_pledged_real+1)~log(backers+1)+duration.c+main_category+country+as.numeric(launched_year)+
            log(usd_goal_real+1),data = df_train)
summary(lr2)
# Residual plot
plot(lr2, which = 1)
# Confidence interval
coefplot(lr2)
kable(head(confint(lr2)))
# Actual vs Fitted
plot(log(df_train$usd_pledged_real), fitted(lr2),xlab="actual value",ylab="fitted values")+
  abline(v=15,h=15,0,1, col="red")
```

```{r }
# Model - add interaction
lr3 <- lm(log(usd_pledged_real+1)~log(backers+1)+duration.c+country+main_category+as.numeric(launched_year)+
            log(usd_goal_real.c+1)+log(backers+1):main_category,data = df_train)
summary(lr3)
# Residual plot
plot(lr3, which = 1)
# Confidence interval
coefplot(lr3)
kable(confint(lr3))
# Actual vs Fitted
plot(log(df_train$usd_pledged_real), fitted(lr3),xlab="actual value",ylab="fitted values")+
  abline(v=15,h=15,0,1, col="red")
```

```{r }
# Model - add quadratic form
lr4 <- lm(log(usd_pledged_real+1)~log(backers+1)+duration.c+duration.c^2+country+main_category+
            as.numeric(launched_year)+log(usd_goal_real+1)+log(backers+1):main_category,data = df_train)
summary(lr4)
# Residual plot
par(mfrow=c(2,2))
plot(lr4)
plot(lr4, which = 1)
residualPlot(lr4)
# Confidence interval
coefplot(lr4)
kable(confint(lr4))
# Actual vs Fitted
plot(log(df_train$usd_pledged_real), fitted(lr4),xlab="actual value",ylab="fitted values")+
  abline(v=15,h=15,0,1, col="red")
# marginalModelPlot(lr4,col=rgb(0,0,0,alpha=0.3),col.line = c("green","red"))
# mmps(lr4,vars=~.,fitted=TRUE)
# avPlots(lr4,id.n=0, id.cex=0.6)

# Outliertest - Detecting the Unusual Data
outlierTest(lr4)
# Influence Index Plot - Influence on regression coefficient
influenceIndexPlot(lr4)
# Leverage - hatvalues
hatvalues(lr4)
leveragePlot(lr4, term.name = )
# SpreadLevel Plot - Detecting heteroscedasticity
  # spreadLevelPlot(lr4)
  bptest(lr4) #Null Hypo=heteroscedasticity exists. P<0.5, therefore reject Null
# Durbin-Watson test - Correlated error
par(mfrow=c(1,3))
plot(1:100,resid(lr4)[1:100]); abline(h=0,lty=2,col="grey",main="fitted vs residual")
acf(resid(lr4))
pacf(resid(lr4))
#dwtest(lr4) #H0: Residuals are not correlated - Small p-value can be used as an evidence against correlated error
```

```{r }
# Deal with zero inflation problem - Two Step model/Hurdle model
# Model zero/non-zero value by using binomial
hd1 <- glm(non_zero~log(backers+1)+duration.c+main_category+country+as.numeric(launched_year)+log(usd_goal_real+1),
           data = df_train_hd, family = "binomial")
summary(hd2)
hd2 <- glm(log(usd_pledged_real)~log(backers+1)+duration.c+main_category+country+as.numeric(launched_year)+
             log(usd_goal_real+1), data = subset(df_train_hd, non_zero==1))

par(mfrow=c(2,2))
plot(hd2)
```


```{r }
set.seed(999)
# Model comparison
anova(lr1,lr2,lr3,lr4)
lrtest(lr1,lr2,lr3,lr4)
pred1 <- predict(lr4, newdata = df_test)
plot(x=pred1, y=log(df_test$usd_pledged_real+1),xlab = "Predicted",ylab = "Actual")+abline(0,1,col="red")
# Inference
# 95% CI for pledged amount
round(confint(lm(usd_pledged_real ~ 1, data=df_train)),2 )
```

# Multilevel Linear Model
```{r warning=FALSE}
# Vary Intercept: category
mllm1 <- lmer(log(usd_pledged_real+1)~log(backers+1)+duration.c+log(usd_goal_real.c+1)+as.numeric(launched_year)
                +(1|main_category),data=df_train)
summary(mllm1)
coefplot(mllm1)
plot_model(mllm1)
# Residual
plot(fitted(mllm1),resid(mllm1,type="pearson"),col="blue")
qqnorm(resid(mllm1))
abline(0,1,col="red")
# Actual vs Fitted
plot(log(df_train$usd_pledged_real), fitted(mllm1),xlab="actual value",ylab="fitted values")
```

```{r }
# Vary Intercept: category and country and launched_year
mllm2 <- lmer(log(usd_pledged_real+1)~log(backers+1)+duration.c+log(usd_goal_real+1)+(1|main_category)+
                (1|country)+as.numeric(launched_year),data=df_train)
summary(mllm2)
# Residual
plot(fitted(mllm2),resid(mllm2,type="pearson"),col="blue")
qqnorm(resid(mllm2))
abline(0,1,col="red")
# Actual vs Fitted
plot(log(df_train$usd_pledged_real), fitted(mllm2),xlab="actual value",ylab="fitted values")
```

```{r }
# Vary Intercept: category and country and launched_year, add another nested random effect category
mllm3 <- lmer(log(usd_pledged_real+1)~log(backers+1)+duration.c+log(usd_goal_real.c+1)+(1|main_category/category)+
                (1|country)+as.numeric(launched_year),data=df_train)
summary(mllm3)
# Residual
plot(fitted(mllm3),resid(mllm3,type="pearson"),col="blue")
qqnorm(resid(mllm3))
abline(0,1,col="red")
# Actual vs Fitted
plot(log(df_train$usd_pledged_real), fitted(mllm3),xlab="actual value",ylab="fitted values")+
  abline(v=15,h=15,0,1, col="red")
```

```{r }
# Vary Intercept and Vary Slope: backers
mllm4 <- lmer(log(usd_pledged_real+1)~log(backers+1)+duration.c+log(usd_goal_real+1)+(1|main_category/category)+
                (1|country)+as.numeric(launched_year),data=df_train)
summary(mllm4)
# Residual
plot(fitted(mllm4),resid(mllm4,type="pearson"),col="blue")
qqnorm(resid(mllm4))
abline(0,1,col="red")
# Actual vs Fitted
plot(log(df_train$usd_pledged_real), fitted(mllm4),xlab="actual value",ylab="fitted values")+
  abline(v=15,h=15,0,1, col="red")
```

```{r }
# Vary Intercept and Vary Slope: backers
mllm5 <- lmer(log(usd_pledged_real+1)~log(backers+1)+duration.c+log(usd_goal_real+1)+
                (1+log(backers+1)|main_category/category)+(1|country)+scale(as.numeric(launched_year)),data=df_train)
summary(mllm5)
# Residual
plot(fitted(mllm5),resid(mllm5,type="pearson"),col="blue")
qqnorm(resid(mllm5))
abline(0,1,col="red")
# Actual vs Fitted
plot(log(df_train$usd_pledged_real), fitted(mllm5),xlab="actual value",ylab="fitted values")+
  abline(v=15,h=15,0,1, col="red")
head(ranef(mllm5))
```

```{r }
# Add interactions
mllm6 <- lmer(log(usd_pledged_real+1)~log(backers+1)+duration.c*log(usd_goal_real+1)+
                (1+log(backers+1)|main_category/category)+(1|country)+as.numeric(launched_year),data=df_train)
summary(mllm6)
# Residual
plot(fitted(mllm6),resid(mllm6,type="pearson"),col="blue")
qqnorm(resid(mllm6))
abline(0,1,col="red")
# Actual vs Fitted
plot(log(df_train$usd_pledged_real), fitted(mllm6),xlab="actual value",ylab="fitted values")+
  abline(v=15,h=15,0,1, col="red")
```

```{r }
# Model comparison
anova(mllm1,mllm2,mllm3,mllm4,mllm5,mllm6)
```

```{r }
nozero <- df_train %>% filter(usd_pledged_real!=0)
df_stan_index <- sample(length(nozero$ID),10000,replace = FALSE)
df_stan <- nozero[df_stan_index,]
mllm5_st <- stan_glmer(log(usd_pledged_real)~log(backers+1)+duration.c+log(usd_goal_real+1)+
                (1+log(backers+1)|main_category/category)+(1|country)+as.numeric(launched_year), 
                       data = df_stan,iter=300,chains=2)
pp_check(mllm5_st, plotfun = "intervals")
```
